/**
 * Hand-written seed for in-bound PO tracker with defaults generated by AI. 
 *
 * Each record puts a specific UI state on screen. Between them they cover all
 * five statuses, both entry points into `exception`, every legal transition and
 * the guards that block the illegal ones.
 *
 * Sea transit is 30-40 days from Asian load ports to the US East Coast. Where a
 * record has both shippedOn and etaOn, the gap sits inside that window.
 */

export const TODAY = '2026-08-25';

export type PurchaseOrderStatus =
  | 'draft'
  | 'confirmed'
  | 'in_transit'
  | 'received'
  | 'exception';

export type ExceptionCode =
  | 'customs_hold'
  | 'vendor_delay'
  | 'short_ship'
  | 'damage'
  | 'documentation';

export interface PurchaseOrderLine {
  sku: string;
  description: string;
  quantity: number;
  unitCostUsd: number;
}

export interface PurchaseOrderException {
  /** The status the PO was in when the exception was raised, and returns to when it clears. */
  raisedFrom: 'confirmed' | 'in_transit';
  raisedOn: string;
  code: ExceptionCode;
  note: string;
}

export interface PurchaseOrder {
  /** Doubles as the route segment: /purchase-orders/PO-2026-1042 */
  poNumber: string;
  status: PurchaseOrderStatus;

  vendor: string;
  brand: string;
  originPort: string;
  destinationPort: string;

  /** Always set. The rest fill in as the PO advances, and are the preconditions
   *  the status machine reads */
  orderedOn: string;
  confirmedOn: string | null;
  shippedOn: string | null;
  etaOn: string | null;
  receivedOn: string | null;

  vessel: string | null;
  containerNumber: string | null;

  lines: PurchaseOrderLine[];
  exception: PurchaseOrderException | null;
}

export const purchaseOrders: PurchaseOrder[] = [
  // Draft, fresh: ordered 6d ago, every downstream date null.
  // Baseline row — confirm is the only legal move and nothing flags.
  {
    poNumber: 'PO-2026-1031',
    status: 'draft',
    vendor: 'Karur Weaves Pvt Ltd',
    brand: 'Hearth & Loom',
    originPort: 'Tuticorin, India',
    destinationPort: 'Savannah, GA',
    orderedOn: '2026-08-19',
    confirmedOn: null,
    shippedOn: null,
    etaOn: null,
    receivedOn: null,
    vessel: null,
    containerNumber: null,
    lines: [
      {
        sku: 'HL-TWL-BATH-600-WHT',
        description: '600gsm Zero-Twist Bath Towel, White, 30x56',
        quantity: 12000,
        unitCostUsd: 6.85,
      },
      {
        sku: 'HL-TWL-HAND-600-WHT',
        description: '600gsm Zero-Twist Hand Towel, White, 16x30',
        quantity: 12000,
        unitCostUsd: 2.95,
      },
      {
        sku: 'HL-TWL-WASH-600-WHT',
        description: '600gsm Zero-Twist Washcloth, White, 13x13',
        quantity: 18000,
        unitCostUsd: 1.1,
      },
    ],
    exception: null,
  },

  // Draft, aged 50d with confirmedOn still null. No ETA to be late against, so
  // attention has to come from a missing date rather than a red one.
  {
    poNumber: 'PO-2026-0994',
    status: 'draft',
    vendor: 'Chattogram Linen Mills Ltd',
    brand: 'Willow & Flax',
    originPort: 'Chittagong, Bangladesh',
    destinationPort: 'Port Elizabeth, NJ',
    orderedOn: '2026-07-06',
    confirmedOn: null,
    shippedOn: null,
    etaOn: null,
    receivedOn: null,
    vessel: null,
    containerNumber: null,
    lines: [
      {
        sku: 'WF-SHT-QN-LIN-OAT',
        description: 'Washed Linen Sheet Set, Queen, Oatmeal',
        quantity: 3200,
        unitCostUsd: 34.5,
      },
      {
        sku: 'WF-SHT-KG-LIN-OAT',
        description: 'Washed Linen Sheet Set, King, Oatmeal',
        quantity: 2100,
        unitCostUsd: 41.0,
      },
      {
        sku: 'WF-PLW-STD-LIN-OAT',
        description: 'Washed Linen Pillowcase Pair, Standard, Oatmeal',
        quantity: 4800,
        unitCostUsd: 11.25,
      },
    ],
    exception: null,
  },

  // Confirmed, healthy: etaOn is a booking, not a tracked arrival — shippedOn is
  // null. Ship enabled, receive blocked. The shape PO-2026-0961 breaks.
  {
    poNumber: 'PO-2026-1018',
    status: 'confirmed',
    vendor: 'Ningbo Fuhua Textile Co., Ltd',
    brand: 'Coastal Linen Co.',
    originPort: 'Ningbo, China',
    destinationPort: 'Savannah, GA',
    orderedOn: '2026-07-28',
    confirmedOn: '2026-08-04',
    shippedOn: null,
    etaOn: '2026-10-05',
    receivedOn: null,
    vessel: null,
    containerNumber: null,
    lines: [
      {
        sku: 'CL-QLT-FQ-COT-SEA',
        description: 'Cotton Voile Quilt, Full/Queen, Seaglass',
        quantity: 4500,
        unitCostUsd: 26.4,
      },
      {
        sku: 'CL-QLT-KG-COT-SEA',
        description: 'Cotton Voile Quilt, King, Seaglass',
        quantity: 2800,
        unitCostUsd: 33.9,
      },
      {
        sku: 'CL-SHM-STD-COT-SEA',
        description: 'Cotton Voile Sham, Standard, Seaglass',
        quantity: 6000,
        unitCostUsd: 7.2,
      },
    ],
    exception: null,
  },

  // Confirmed 62d ago, booked ETA 5d out, still never shipped.
  // The guard case: receive is gated on shippedOn
  {
    poNumber: 'PO-2026-0961',
    status: 'confirmed',
    vendor: 'Indus Terry Mills (Pvt) Ltd',
    brand: 'Marlowe Home',
    originPort: 'Karachi, Pakistan',
    destinationPort: 'Norfolk, VA',
    orderedOn: '2026-06-15',
    confirmedOn: '2026-06-24',
    shippedOn: null,
    etaOn: '2026-08-30',
    receivedOn: null,
    vessel: null,
    containerNumber: null,
    lines: [
      {
        sku: 'MH-TWL-SHT-700-SLT',
        description: '700gsm Turkish-Style Bath Sheet, Slate, 35x70',
        quantity: 8000,
        unitCostUsd: 11.6,
      },
      {
        sku: 'MH-MAT-BATH-COT-SLT',
        description: 'Reversible Cotton Bath Mat, Slate, 21x34',
        quantity: 9500,
        unitCostUsd: 5.4,
      },
    ],
    exception: null,
  },

  // In transit, on schedule: ETA 24d out. First record with vessel and container
  // populated. Reference point for the two below, which differ only in etaOn.
  {
    poNumber: 'PO-2026-1004',
    status: 'in_transit',
    vendor: 'Nantong Sunrise Home Textile Co.',
    brand: 'Hearth & Loom',
    originPort: 'Shanghai, China',
    destinationPort: 'Port Elizabeth, NJ',
    orderedOn: '2026-07-10',
    confirmedOn: '2026-07-17',
    shippedOn: '2026-08-14',
    etaOn: '2026-09-18',
    receivedOn: null,
    vessel: 'MSC Aurora',
    containerNumber: 'MSCU7418823',
    lines: [
      {
        sku: 'HL-DUV-FQ-SAT-IVY',
        description: '400TC Sateen Duvet Cover, Full/Queen, Ivory',
        quantity: 5200,
        unitCostUsd: 19.8,
      },
      {
        sku: 'HL-DUV-KG-SAT-IVY',
        description: '400TC Sateen Duvet Cover, King, Ivory',
        quantity: 3400,
        unitCostUsd: 24.6,
      },
      {
        sku: 'HL-PLW-KG-SAT-IVY',
        description: '400TC Sateen Pillowcase Pair, King, Ivory',
        quantity: 7000,
        unitCostUsd: 6.15,
      },
    ],
    exception: null,
  },

  // In transit, ETA 3d out. Same shape as PO-2026-1004 but must badge and sort
  // differently — "arriving" is a computed band, not a stored flag.
  {
    poNumber: 'PO-2026-0972',
    status: 'in_transit',
    vendor: 'Panipat Home Mills Ltd',
    brand: 'Anchor Bay Home',
    originPort: 'Mundra, India',
    destinationPort: 'Savannah, GA',
    orderedOn: '2026-06-22',
    confirmedOn: '2026-06-29',
    shippedOn: '2026-07-24',
    etaOn: '2026-08-28',
    receivedOn: null,
    vessel: 'Maersk Sentosa',
    containerNumber: 'MAEU4491077',
    lines: [
      {
        sku: 'AB-THR-50X60-COT-NVY',
        description: 'Herringbone Cotton Throw, 50x60, Navy',
        quantity: 7500,
        unitCostUsd: 9.3,
      },
      {
        sku: 'AB-BLK-FQ-WOV-NVY',
        description: 'Woven Cotton Blanket, Full/Queen, Navy',
        quantity: 4200,
        unitCostUsd: 16.75,
      },
    ],
    exception: null,
  },

  // In transit, ETA 16d past and not received — the only negative countdown.
  {
    poNumber: 'PO-2026-0948',
    status: 'in_transit',
    vendor: 'Mekong Loom Textile JSC',
    brand: 'Willow & Flax',
    originPort: 'Ho Chi Minh City, Vietnam',
    destinationPort: 'Charleston, SC',
    orderedOn: '2026-06-01',
    confirmedOn: '2026-06-08',
    shippedOn: '2026-07-02',
    etaOn: '2026-08-09',
    receivedOn: null,
    vessel: 'ONE Meridian',
    containerNumber: 'ONEU6203514',
    lines: [
      {
        sku: 'WF-SHC-72X72-WAF-FLX',
        description: 'Waffle Weave Shower Curtain, 72x72, Flax',
        quantity: 6800,
        unitCostUsd: 8.2,
      },
      {
        sku: 'WF-RUG-BATH-TUF-FLX',
        description: 'Tufted Cotton Bath Rug, 24x40, Flax',
        quantity: 5400,
        unitCostUsd: 12.9,
      },
    ],
    exception: null,
  },

  // Exception raised from in_transit.
  {
    poNumber: 'PO-2026-0983',
    status: 'exception',
    vendor: 'Coromandel Textiles Pvt Ltd',
    brand: 'Coastal Linen Co.',
    originPort: 'Chennai, India',
    destinationPort: 'Savannah, GA',
    orderedOn: '2026-06-05',
    confirmedOn: '2026-06-12',
    shippedOn: '2026-07-08',
    etaOn: '2026-08-12',
    receivedOn: null,
    vessel: 'CMA CGM Andaman',
    containerNumber: 'CMAU5138462',
    lines: [
      {
        sku: 'CL-SHT-QN-400-WHT',
        description: '400TC Sateen Sheet Set, Queen, White',
        quantity: 6000,
        unitCostUsd: 21.4,
      },
      {
        sku: 'CL-SHT-KG-400-WHT',
        description: '400TC Sateen Sheet Set, King, White',
        quantity: 3800,
        unitCostUsd: 26.9,
      },
    ],
    exception: {
      raisedFrom: 'in_transit',
      raisedOn: '2026-08-14',
      code: 'customs_hold',
      note: 'Container pulled for intensive CBP exam at Savannah. Broker has filed responses; awaiting release.',
    },
  },

  // Exception raised from confirmed, never sailed. Same status as PO-2026-0983
  // but clears somewhere else.
  {
    poNumber: 'PO-2026-1009',
    status: 'exception',
    vendor: 'Ravi Cotton Industries',
    brand: 'Marlowe Home',
    originPort: 'Karachi, Pakistan',
    destinationPort: 'Port Elizabeth, NJ',
    orderedOn: '2026-07-13',
    confirmedOn: '2026-07-20',
    shippedOn: null,
    etaOn: '2026-09-25',
    receivedOn: null,
    vessel: null,
    containerNumber: null,
    lines: [
      {
        sku: 'MH-TWL-BATH-550-SND',
        description: '550gsm Ringspun Bath Towel, Sand, 27x52',
        quantity: 14000,
        unitCostUsd: 5.6,
      },
      {
        sku: 'MH-TWL-HAND-550-SND',
        description: '550gsm Ringspun Hand Towel, Sand, 16x28',
        quantity: 14000,
        unitCostUsd: 2.4,
      },
      {
        sku: 'MH-TWL-WASH-550-SND',
        description: '550gsm Ringspun Washcloth, Sand, 13x13',
        quantity: 20000,
        unitCostUsd: 0.95,
      },
    ],
    exception: {
      raisedFrom: 'confirmed',
      raisedOn: '2026-08-18',
      code: 'short_ship',
      note: 'Vendor can only fill 60% of the towel quantity for the booked sailing. Decision needed: split the shipment or hold for the full order.',
    },
  },

  // Received: nothing null, no legal transition left.
  {
    poNumber: 'PO-2026-0925',
    status: 'received',
    vendor: 'Shaoxing Jinhe Weaving Co.',
    brand: 'Anchor Bay Home',
    originPort: 'Ningbo, China',
    destinationPort: 'Norfolk, VA',
    orderedOn: '2026-05-11',
    confirmedOn: '2026-05-18',
    shippedOn: '2026-06-11',
    etaOn: '2026-07-16',
    receivedOn: '2026-07-20',
    vessel: 'Ever Vantage',
    containerNumber: 'EGHU9074128',
    lines: [
      {
        sku: 'AB-TBL-RUN-14X72-LIN',
        description: 'Linen Blend Table Runner, 14x72, Natural',
        quantity: 6500,
        unitCostUsd: 4.8,
      },
      {
        sku: 'AB-TBL-NAP-20X20-LIN',
        description: 'Linen Blend Napkin Set of 4, 20x20, Natural',
        quantity: 9000,
        unitCostUsd: 6.2,
      },
      {
        sku: 'AB-TBL-PLM-13X19-LIN',
        description: 'Linen Blend Placemat Set of 4, 13x19, Natural',
        quantity: 7200,
        unitCostUsd: 5.35,
      },
    ],
    exception: null,
  },
];
